name: Example_Plugin
version: 0.1
main: com.shortway.exampleplugin.ExamplePlugin
api-version: 1.13

commands:
  example:
    description: This is where you can test our Example Plugin!

  hunger:
    description: /hunger <food-level>
